---
title: "CCBR1155_Analysis"
author: "Samantha Sevilla"
date: "4/15/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r echo=FALSE, warning=FALSE, include=FALSE}
packages=c("dplyr","ggplot2","ggpubr","ComplexUpset","msigdbr","clusterProfiler")
invisible(lapply(packages, library, character.only = TRUE))
```

```{r echo=FALSE, warning=FALSE, include=FALSE}
#paths
parent_dir="~/../../Volumes/projects/ccbr1155/CS030586_CARAP/results/peaks/contrasts/"
out_dir = "~/../../Volumes/projects/ccbr1155/CS030586_CARAP/results/peaks/contrasts/ora_results"

#sample list
file_list=c("siSmyd3_2m_Smyd3_0.25HCHO_500K_vs_siNC_2m_Smyd3_0.25HCHO_500K__dedup__norm.relaxed.bed",
            "siSmyd3_2m_Smyd3_0.25HCHO_500K_vs_siNC_2m_Smyd3_0.25HCHO_500K__dedup__norm.stringent.bed",
            "siSmyd3_2m_Smyd3_0.25HCHO_500K_vs_siNC_2m_Smyd3_0.25HCHO_500K__dedup__narrowPeak",
            "siSmyd3_2m_Smyd3_0.25HCHO_500K_vs_siNC_2m_Smyd3_0.25HCHO_500K__no_dedup__norm.relaxed.bed",
            "siSmyd3_2m_Smyd3_0.25HCHO_500K_vs_siNC_2m_Smyd3_0.25HCHO_500K__no_dedup__norm.stringent.bed",
            "siSmyd3_2m_Smyd3_0.25HCHO_500K_vs_siNC_2m_Smyd3_0.25HCHO_500K__no_dedup__narrowPeak",
            "siSmyd3_5m_Smyd3_0.25HCHO_500K_vs_siNC_5m_Smyd3_0.25HCHO_500K__dedup__norm.relaxed.bed",
            "siSmyd3_5m_Smyd3_0.25HCHO_500K_vs_siNC_5m_Smyd3_0.25HCHO_500K__dedup__norm.stringent.bed",
            "siSmyd3_5m_Smyd3_0.25HCHO_500K_vs_siNC_5m_Smyd3_0.25HCHO_500K__dedup__narrowPeak",
            "siSmyd3_5m_Smyd3_0.25HCHO_500K_vs_siNC_5m_Smyd3_0.25HCHO_500K__no_dedup__norm.relaxed.bed",
            "siSmyd3_5m_Smyd3_0.25HCHO_500K_vs_siNC_5m_Smyd3_0.25HCHO_500K__no_dedup__norm.stringent.bed",
            "siSmyd3_5m_Smyd3_0.25HCHO_500K_vs_siNC_5m_Smyd3_0.25HCHO_500K__no_dedup__narrowPeak")

#set global variables
p_val_set = 0.05
species = "mouse"
log2fc_set = log(1.5,2)
```

```{r echo=FALSE}
#read in results file, add to df
method="fragments"
merged_df=data.frame()
for (sample_id in file_list){
  # read in results and filter
  # pvalue <0.05, log2FoldChange +- log2(1.5)
  raw_df=read.csv(paste0(parent_dir,sample_id,"/",sample_id,"_",method,"based_diffresults.txt"),sep = "\t")
  filt_df=subset(raw_df,pvalue<p_val_set)
  filt_df=subset(filt_df,(log2FoldChange>=log2fc_set) | (log2FoldChange<=-log2fc_set))
  
  #add metadata
  filt_df$sample=gsub("_Smyd3_0.25HCHO_500K","",strsplit(sample_id,"__")[[1]][1])
  filt_df$dedup=strsplit(sample_id,"__")[[1]][2]
  filt_df$type=strsplit(strsplit(sample_id,"__")[[1]][3],"[.]")[[1]][2]
  filt_df$type=filt_df$type %>% replace(is.na(.),"narrowPeak")
  filt_df$method=method
  filt_df$total=nrow(filt_df)
  filt_df$uniqueid=paste0(filt_df$sample,"_",filt_df$dedup,"_",filt_df$type)
  
  #merge dfs
  merged_df=rbind(merged_df,filt_df)
}

# collapse to get shortAnno counts
collapsed_df=merged_df %>% count(sample,shortAnno,dedup,type,method,total,uniqueid)

#calculate percentages
collapsed_df$perc=round((collapsed_df$n/collapsed_df$total)*100,2)

```

######################################################################
# Bar plots
######################################################################

```{r echo=FALSE, warning=FALSE}
#Create bargraph of totals
ggplot(collapsed_df,aes(x=dedup,y=total,fill=sample))+
  geom_bar(stat = "identity")+
  facet_grid(type~sample) +
  ylab("n occurances") +
  ggtitle("Number of significant peaks\nby analytical method") +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  geom_text(aes(label = total), vjust = -2)

#Create bargraph of percents
ggplot(collapsed_df,aes(x=dedup,y=perc,fill=shortAnno))+
  geom_bar(stat = "identity")+
  facet_grid(type~sample) +
  ylab("Percent of occurances") +
  ggtitle("Percent of significant peaks type\nby analytical method") +
  scale_x_discrete(guide = guide_axis(angle = 90))

subset(collapsed_df,shortAnno=="Intron" | shortAnno=="Promoter") %>%
  ggplot(aes(x=dedup,y=perc,fill=shortAnno,label=perc))+
  geom_bar(stat = "identity")+
  facet_grid(type~sample) +
  ylab("Percent of occurances") +
  ggtitle("Percent of significant peaks type subset\nby analytical method") +
  scale_x_discrete(guide = guide_axis(angle = 90))+
  geom_text(size = 3, position = position_stack(vjust = 0.5))
```

######################################################################
# UPSET Plots
######################################################################

```{r echo=FALSE}
create_upset_plots<-function(df_in,title_in){
  up_df=data.frame()
  
  for (sample_id in unique(df_in$uniqueid)){
    #subset df
    tmp_df=subset(df_in,uniqueid==sample_id)
    tmp_df=tmp_df[complete.cases(tmp_df),]
    
    #add counts of shortAnno
    for (rowid in rownames(tmp_df)){
      up_df[tmp_df[rowid,"SYMBOL"],sample_id]=1
      up_df[tmp_df[rowid,"SYMBOL"],"shortAnno"]=tmp_df[rowid,"shortAnno"]
    }
  }
  
  #shorten name
  colnames(up_df)=gsub("m_dedup_relaxed","m",colnames(up_df))
  colnames(up_df)=gsub("m_no_dedup_relaxed","m",colnames(up_df))
  colnames(up_df)=gsub("m_dedup_stringent","m",colnames(up_df))
  colnames(up_df)=gsub("m_no_dedup_stringent","m",colnames(up_df))
  colnames(up_df)=gsub("m_dedup_narrowPeak","m",colnames(up_df))
  colnames(up_df)=gsub("m_no_dedup_narrowPeak","m",colnames(up_df))
  
  # set NA to 0
  up_df = up_df %>% replace(is.na(.), 0)
  
  # plot
  p=upset(
      up_df,
      colnames(up_df)[c(1,3:ncol(up_df))],
      sort_sets='ascending',
      base_annotations=list(
        'Intersection size'=intersection_size(
            text_colors=c(
                on_background='brown', on_bar='yellow'
            )
        )
        + annotate(
            geom='text', x=Inf, y=Inf,
            label=title_in,
            vjust=1, hjust=1
        )
        + ylab('Intersection size')
    ), annotations = list(
          'Annotation'=(
              ggplot(mapping=aes(fill=shortAnno))
              + geom_bar(stat='count', position='fill')
              + scale_y_continuous(labels=scales::percent_format())
              + ylab('Annotation Category')
          )
      ),
      width_ratio=0.1,
      set_sizes=FALSE
  )
  print(p)
}
sample_list=c("siSmyd3_2m_vs_siNC_2m_dedup_relaxed","siSmyd3_5m_vs_siNC_5m_dedup_relaxed")
create_upset_plots(subset(merged_df,uniqueid %in% sample_list), "Relaxed - Dedup")

sample_list=c("siSmyd3_2m_vs_siNC_2m_no_dedup_relaxed","siSmyd3_5m_vs_siNC_5m_no_dedup_relaxed")
create_upset_plots(subset(merged_df,uniqueid %in% sample_list), "Relaxed - No Dedup")

sample_list=c("siSmyd3_2m_vs_siNC_2m_dedup_stringent","siSmyd3_5m_vs_siNC_5m_dedup_stringent")
create_upset_plots(subset(merged_df,uniqueid %in% sample_list), "Stringent - Dedup")

sample_list=c("siSmyd3_2m_vs_siNC_2m_no_dedup_stringent","siSmyd3_5m_vs_siNC_5m_no_dedup_stringent")
create_upset_plots(subset(merged_df,uniqueid %in% sample_list), "Stringent - No Dedup")

sample_list=c("siSmyd3_2m_vs_siNC_2m_dedup_narrowPeak","siSmyd3_5m_vs_siNC_5m_dedup_narrowPeak")
create_upset_plots(subset(merged_df,uniqueid %in% sample_list), "narrowPeak - Dedup")

sample_list=c("siSmyd3_2m_vs_siNC_2m_no_dedup_narrowPeak","siSmyd3_5m_vs_siNC_5m_no_dedup_narrowPeak")
create_upset_plots(subset(merged_df,uniqueid %in% sample_list), "narrowPeak - No Dedup")
```

######################################################################
# Heatmaps
######################################################################

```{r echo=FALSE, warning=FALSE}
create_heat_maps<-function(feature_in, sample_list,title_in){
  
  #subset for feature and samples
  sub_df=subset(merged_df,shortAnno==feature_in & uniqueid %in% sample_list)
  sub_df=sub_df[complete.cases(sub_df),]
  
  #for each sample log2foldchange values for each gene
  heatmap_df=data.frame()
  for(rowid in rownames(sub_df)){
    sample_id=sub_df[rowid,"uniqueid"]
    gene_id=sub_df[rowid,"SYMBOL"]
    heatmap_df[sample_id,gene_id]=sub_df[rowid,"log2FoldChange"]
  }

  # shorten rownames
  rownames(heatmap_df)=gsub("_relaxed","",rownames(heatmap_df))
  rownames(heatmap_df)=gsub("_stringent","",rownames(heatmap_df))
  rownames(heatmap_df)=gsub("_narrowPeak","",rownames(heatmap_df))
  rownames(heatmap_df)=gsub("_dedup","",rownames(heatmap_df))
  rownames(heatmap_df)=gsub("_no","",rownames(heatmap_df))
  
  #set colors
  paletteLength <- 1000
  mycolors <- colorRampPalette(c("blue","white","red"), interpolate = "linear")(paletteLength)
  
  # scale
  
  scale_df= t(scale(t(heatmap_df)))
  scale_df=as.matrix(scale_df %>% replace(is.na(.), 0))
  
  if(ncol(scale_df)<90){
    pheatmap::pheatmap(scale_df, 
             scale = "none", main=title_in,
             fontsize = 10, fontsize_row = 6, fontsize_col = 6, color = mycolors, 
             border_color = "NA",
             legend_breaks = c(-5,-4,-3,-2,-1,0,1,2,3,4,5))
  }else{
    pheatmap::pheatmap(scale_df, 
             scale = "none", main=title_in,
             fontsize = 10, fontsize_row = 6, fontsize_col = 6, color = mycolors, 
             border_color = "NA",
             legend_breaks = c(-5,-4,-3,-2,-1,0,1,2,3,4,5),
             show_colnames = FALSE)
  }
}

feature_list=c("Promoter","Intron")
for (feature_id in feature_list){
  create_heat_maps(feature_id,c("siSmyd3_2m_vs_siNC_2m_dedup_relaxed","siSmyd3_5m_vs_siNC_5m_dedup_relaxed"),
                      paste0(feature_id," Genes: Relaxed - Dedup"))
  create_heat_maps(feature_id,c("siSmyd3_2m_vs_siNC_2m_no_dedup_relaxed","siSmyd3_5m_vs_siNC_5m_no_dedup_relaxed"),
                      paste0(feature_id," Genes: Relaxed - Non-Dedup"))
  create_heat_maps(feature_id,c("siSmyd3_2m_vs_siNC_2m_dedup_stringent","siSmyd3_5m_vs_siNC_5m_dedup_stringent"),
                      paste0(feature_id," Genes: Stringent - Dedup"))
  create_heat_maps(feature_id,c("siSmyd3_2m_vs_siNC_2m_no_dedup_stringent","siSmyd3_5m_vs_siNC_5m_no_dedup_stringent"),
                      paste0(feature_id," Genes: Stringent - Non-Dedup"))
  create_heat_maps(feature_id,c("siSmyd3_2m_vs_siNC_2m_dedup_narrowPeak","siSmyd3_5m_vs_siNC_5m_dedup_narrowPeak"),
                      paste0(feature_id," Genes: narrowPeak - Dedup"))
  create_heat_maps(feature_id,c("siSmyd3_2m_vs_siNC_2m_no_dedup_narrowPeak","siSmyd3_5m_vs_siNC_5m_no_dedup_narrowPeak"),
                      paste0(feature_id," Genes: narrowPeak - Non-Dedup"))
}
```

######################################################################
# ORA/GSEA
######################################################################

```{r functions, include=FALSE}
######################################################################
# ORA/GSEA Functions
######################################################################
readdegfile<-function(fn){
  x=read.csv(fn,header=TRUE,sep="\t")
  return(as.data.frame(x))
}

deg2geneList<-function(deg){
  gl=as.data.frame(deg$gsea_ranking_score)
  gl$GN=deg$gene
  colnames(gl)=c("Rank","GeneName")
  gl$absRank=abs(gl$Rank)
  gl=gl[order(gl$absRank,decreasing = TRUE),]
  gl=gl[match(unique(gl$GeneName),gl$GeneName),]
  geneList=gl$Rank
  names(geneList)=as.character(gl$GeneName)
  geneList <- sort(geneList, decreasing = TRUE)
  return(geneList)
}

ora_plus_plot <- function(gl,t2g,ttl,fn){
  result=enricher(gene=gl, TERM2GENE=t2g, pvalueCutoff = 1)
  resultdf=as.data.frame(result)
  write.table(resultdf,file=fn,quote=FALSE,sep="\t",row.names = FALSE,col.names = TRUE)
  
  if(nrow(resultdf)==0){
    print("No sig results for ORA")
    p1 = ggparagraph(
      paste0("\n\n\n No Sig Results"),
      color = NULL,
      size = 20,
      face = "bold",
      family = NULL,
      lineheight = NULL
    )
  } else{
    p1 = dotplot(result,title=ttl,font.size = 8, showCategory=10)
  }
  return(p1)
}

save_plots<-function(p1,p2,p3="",contrast_id,file_name){
  if(p3=="none"){
    mypdf <- cowplot::plot_grid(p1, p2, ncol=1, labels=LETTERS[1:2])
    print(mypdf)
    ggsave(filename = paste(out_dir, contrast_id, "/", contrast_id, file_name, sep=""), 
           height = 8.90, width = 12.80, device = "png", plot = mypdf)
  } else{
    mypdf <- cowplot::plot_grid(p1, p2, p3, ncol=1, labels=LETTERS[1:3])
    print(mypdf)
    ggsave(filename = paste(out_dir, "cluster_", cluster_id, "/", contrast_id, "_",version_id, "/", contrast_id, file_name, sep=""), 
           height = 8.90, width = 12.80, device = "png", plot = mypdf)
  }
}

main_function<-function(deg_file,out_dir,contrast_id){
  
  # read deg
  deg=readdegfile(deg_file)
  
  #create output dir if needed
  dir.create(file.path(out_dir), showWarnings = FALSE)

  #subset significant genes for ORA
  siggenes=deg[deg$pvalue <= p_val_set & (deg$log2FoldChange < (-1*log2fc_set) | deg$log2FoldChange > log2fc_set),]
  sigGeneList=siggenes$SYMBOL
  
  #generate gene lists for C2 with subtypes biocarta, kegg, reactome, wiki
  c2b=msigdbr(species = species, category = "C2", subcategory = "BIOCARTA") %>% 
    dplyr::select(gs_name,gene_symbol)
  
  c2k=msigdbr(species = species, category = "C2", subcategory = "KEGG") %>% 
    dplyr::select(gs_name,gene_symbol)
  
  c2r=msigdbr(species = species, category = "C2", subcategory = "REACTOME") %>%
    dplyr::select(gs_name,gene_symbol)
  
  c2w=msigdbr(species = species, category = "C2", subcategory = "WIKIPATHWAYS") %>%
    dplyr::select(gs_name,gene_symbol)
  
  #generate gene lists for C5 with subtypes MF, BP, CC
  c5gomf=msigdbr(species = species,  category = "C5", subcategory = "GO:MF") %>% dplyr::select(gs_name,gene_symbol)
  c5gobp=msigdbr(species = species,  category = "C5", subcategory = "GO:BP") %>% dplyr::select(gs_name,gene_symbol)
  c5gocc=msigdbr(species = species,  category = "C5", subcategory = "GO:CC") %>% dplyr::select(gs_name,gene_symbol)
  
  ## C2:BIOCARTA
  print("Results for BIOCARTA")
  p1 = ora_plus_plot(gl=sigGeneList,t2g=c2b,ttl=paste0("ORA:C2:BIOCARTA - ",contrast_id),
                     fn=paste(out_dir,contrast_id,".c2b.ora.results.txt",sep=""))

  ## C2:KEGG
  print("Results for KEGG")
  p2 = ora_plus_plot(gl=sigGeneList,t2g=c2k,ttl=paste0("ORA:C2:KEGG - ",contrast_id),
                     fn=paste(out_dir,contrast_id,".c2k.ora.results.txt",sep=""))
  save_plots(p1,p2,"none",contrast_id,".c2bk.dotplot.png")

  ## C2:REACTOME
  print("Results for REACTOME")
  p1 = ora_plus_plot(gl=sigGeneList,t2g=c2r,ttl=paste0("ORA:C2:REACTOME - ",contrast_id),
                     fn=paste(out_dir,contrast_id,".c2r.ora.results.txt",sep=""))
  
  ## C2:WIKIPATHWAYS
  print("Results for WIKIPATHWAYS")
  p2 = ora_plus_plot(gl=sigGeneList,t2g=c2w,ttl=paste0("ORA:C2:WIKIPATHWAYS - ",contrast_id),
                   fn=paste(out_dir,contrast_id,".c2w.ora.results.txt",sep=""))
  save_plots(p1,p2,"none",contrast_id,".c2rw.dotplot.png")

  ## C5:GO:MF
  print("Results for GO:MF")
  p1 = ora_plus_plot(gl=sigGeneList,t2g=c5gomf,ttl=paste0("ORA:GO:MF - ",contrast_id),
                   fn=paste(out_dir,contrast_id,".c5gomf.ora.results.txt",sep=""))

  ## C5:GO:BP
  print("Results for GO:BP")
  p2 = ora_plus_plot(gl=sigGeneList,t2g=c5gobp,ttl=paste0("ORA:GO:BP - ",contrast_id),
                   fn=paste(out_dir,contrast_id,".c5gobp.ora.results.txt",sep=""))
  save_plots(p1,p2,"none",contrast_id,".c5gomfbp.dotplot.png")

  ## C5:GO:CC
  print("Results for GO:CC")
  p1 = ora_plus_plot(gl=sigGeneList,t2g=c5gocc,ttl=paste0("ORA:GO:CC - ",contrast_id),
                   fn=paste(out_dir,contrast_id,".c5gocc.ora.results.txt",sep=""))
  save_plots(p1,"","none",contrast_id,".c5gocc.dotplot.png")
}
```

```{r setup, include=FALSE}
#####################################
# ORA Run
#####################################
for (sample_id in file_list){
  sub_sample_id=strsplit(sample_id,"_no")[[1]][1]
  sub_sample_id=strsplit(sub_sample_id,"_de")[[1]][1]
  sub_sample_id=gsub("_Smyd3_0.25HCHO_500K_","",sub_sample_id)
  sub_sample_id=gsub("mvs","m_vs",sub_sample_id)
  
  print(sample_id)
  main_function(deg_file = paste0(parent_dir,sample_id,"/",sample_id,"_",method,"based_diffresults.txt"), 
       out_dir = paste0(out_dir,sub_sample_id,"/"),
       contrast_id = paste0("\n",sub_sample_id))

}
```
